os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
#  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: Dw2l7CHGbkavrFRA2k9YRJ7/+auYw8n4D1vwD7o9Ltv+STPTy/yvHgcLkCNcUBruWXRUiJhVrAk5dK/J7p8Qc6BwAe5OWKxU2+BApZwmusDhex/41g8khqDkP2ladyJWcDmm8dkVP9qnJg7ZbOaJgYDWsyvAw0pRgu95RL6ag1KVdNsWJHwxIvNFLu2CzRhgIKA3FFccPvtpjM2w6pXd2/DLUisSne68XGZE7RYP9GPr5EIV9n71uVkJauVEF3ehA7XIG3eRbEdaFsMminOKUGeWOZXn/mclvBkHTKxqEyYABsFPbg7QA9ZXZICm50LZx8ln7WKPDenEhF+qyGgHaJ3TGbOyfEvq3i3RdVRz1lKg4sJazOYaegb5fw04tBUCAiJS2RvKZnn9n7ccD65F+IABSl6MmkTS2ly+fS8B/5p+qTkCoChy33nbMl1l04of0YuSbEgWaqnmVKwi+YXDM4H1lWiWjmqWAZAYT+BNnYoIe6umG3ye+D3NAdYDL1q09CN2rciDfR6zfcVibasIg9tWry2H3askJMZppROskLuErMujSGP4ydBnfDPGcOtNRl2s5Hf2U36RDiPjiT2N+FHJCPPfhptxrXy2lWY04Go9dY6pHzUCZuLoeKiPikqNz2W2x/h8XizWHuq+s9Y4NyDrfzpIC56eWkb+gdXZW3A=
  - secure: ZtY2Usqvyypuc5l34ov4oiIRUdph2yc4/a3k+tKim1G+/qhuD49btscoZJgq6AKHbyEzaCLZCT/lDvvdZUtLhraofCffZfU5hnNp2nIZSGhR5aIcMyCuH93WJ+446vZXdgXI0S7VRKu8Y0tvhvZMke3I2pQfbhg7jSEt3HLJMiyuAueBKgdX0x7BaOZEYmlH9mMXkyBVtpD8kBP63itz2YbQbSlq4aXBvl2Lk7O5LYto6BwFgW/Z8IVX7L6cLqPY8xnIFl8BvDl4wpAHmfqJl7vyAT4HmVemucDzPUgSRsc0jKYodY5m3o6kDqrYL+9Mp2/cwy/32MkrVq3llmon34EmgflY0lhhI8pSOC6U4C9mh+YexDthQ5PGSjWY1CPvHBwTr3JnWfSpeHQ4X6BKavzpL4aWWJaEq2yjw7tROvRso3vQla3QV5R4v3Pw+pWvqEjEMFT8qT2Inh+KD7xCd9H0NFeuSpWqy0UoMsblI3Jb2hbNIpkT4BYaLlZ+qBfDj3EPtExJhISmVREZREtXp7iJOiGLchNtUOXhTSk7ChY9QepL6mvsqvyEUU/Ae6fimr+wAYhHMTpECb0AfpIztYzJ737QoCFc2Iw+pJ9r/83qjrmQp1VVQ+dZQuEcJs/6/yH4S4IB3RVgj4nIPKwskFFVPN4j0sM3zrGBdOEPZ/Q=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
